### ISSUE TITLE
[REQ] license setting on GH

### ISSUE THREAD

**Issue by forart** [micknoise/Maximilian#105]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Audio libraries > DSPs section](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md#dsps)), can you please set correct licensing terms on this git ?

Our "problem" is that does not generates the correct badge: 

![](https://flat.badgen.net/github/license/micknoise/Maximilian?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/micknoise/Maximilian/?label=LICENSE)

...maybe it's a GH setup issue ?

Thanks in advance.

**Comment by chriskiefer** [comment]
i added a license.txt file, does that help?

**Comment by forart** [comment]
Hi there, as you can see above now the badge is generated correctly.

If you have some spare time, let us know what you think about re-organization (not yet applied on [Audio DSP section](https://github.com/forart/HyMPS/blob/main/AudioDSPs.md) where Maximilian is listed)

Thanks !
