### ISSUE TITLE
Undefined symbols for architecture i386:

### ISSUE THREAD

**Issue by caseybasichis** [micknoise/Maximilian#13]
Hi,

I'm getting an error.  I'm building for ios.  I added the Maximillian directory to the header and library search paths.

I'm just using an extremely basic setup with 

#include "maximilian.h"
maxiOsc mySine;//let's create an oscillator and give it a name.
mySine.sinewave(440);  // <- this is being assigned to a buffer in a loop

I get the errors:

Undefined symbols for architecture i386:
  "maxiOsc::maxiOsc()", referenced from:
      SoFancyApp::SoFancyApp() in SoFancyApp.o
  "maxiOsc::sinewave(double)", referenced from:
      SoFancyApp::outputCallback(int, float*, double) in SoFancyApp.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea why this is happening?

Thanks,
Casey

**Comment by TheNorthEestern** [comment]
I'm encountering the same issue despite having Accelerate installed. I'm building for OS X Yosemite.

![screenshot 2015-02-28 16 52 36](https://cloud.githubusercontent.com/assets/59484/6428289/4013fce0-bf6a-11e4-846c-5c67bf71f3da.png)

Any ideas?
