### ISSUE TITLE
Phase Vocoder Example?

### ISSUE THREAD

**Issue by JoshuaBatty** [micknoise/Maximilian#21]
Hey Mick going back a few years to you mentioned in the oF forum and in you paper on Maximilian released in 2010 in the future work section that you were aiming to make a phase vocoder example with Maxi. Just wondering if you had made a start on this yet or if you had even an alpha version I would be able to take a look at. Really looking to extend my audiovisual granular app to include phase vocoding so I can mess with integrating it with visual slit scanning. Would love to be able to do this with Maxi if possible.

Any news? Cheers.

**Comment by micknoise** [comment]
Hi Josh

Just to let you know the example is ready I am adding it very soon. Thanks for asking me about it, it's genuinely appreciated :-) Sorry it took so long...

**Comment by JoshuaBatty** [comment]
Fantastic thanks Mick! Good things come to those who wait. Looking forward to taking the Kadenze course :)
