### ISSUE TITLE
Crash in MaxiSample::Read

### ISSUE THREAD

**Issue by Ahbee** [micknoise/Maximilian#22]
When reading the first channel from a 2 channel file, the read function crashes.
this code seems wrong

```
if (myChannels>1) {
            int position=0;
            int channel=readChannel*2;
            for (int i=channel;i<myDataSize +6;i+=(myChannels*2)) {
                myData[position]=myData[i];
                myData[position+1]=myData[i+1];
                position+=2;
       }
}
```

I removed the +6 from this line and so the crash no longer occurs;

```
for (int i=channel;i < myDataSize +6;i+=(myChannels*2)
```

so now it looks like this

```
for (int i=channel;i<myDataSize ;i+=(myChannels*2) // removed +6
```

why is that +6 there? the index of myData should not go beyond myDataSize?

**Comment by enedrio** [comment]
I just ran into this. Is there any good reason why it's still in the current version?

**Comment by micknoise** [comment]
Apologies - fixed.
