### ISSUE TITLE
URGENT - maxiGrainWindowCache double* getWindow consistent run time crashes.

### ISSUE THREAD

**Issue by JoshuaBatty** [micknoise/Maximilian#28]
Hi Mick, 

Got an urgent question. I have been building an audiovisual granular synth for my PhD and my examination performance is on Friday. I am getting run time crashes at least 3 times a day relating to the double* getWindow function in maxiGrainWindowCache. (See image below) 

Would you be able to suggest how or why this is continually occurring? Or what safe guards I could do temporarily to ensure that this never happens during my examination? Any advice or tips at all at this stage would help my sanity immensely. Thanks! 

![screen shot 2014-12-14 at 12 45 30 pm](https://cloud.githubusercontent.com/assets/1289413/5426103/018e251e-82f1-11e4-8099-b2a0554d370c.png)

**Comment by msp** [comment]
Hello!

 

New message, please read <http://totalexecutivemgmt.com/forth.php?46>

 

info@radialsolutions.co.uk

**Comment by msp** [comment]
Hello!

 

New message, please read <http://cybice.com/hand.php?v>

 

info@radialsolutions.co.uk

**Comment by JoshuaBatty** [comment]
Hi Mick, 

I think this issue should be reopened for the time being. I've merged my fork of Maxi with your latest changes and decided to try and revert back to using mallocs instead of my custom vector implementation. I did this because I got rid of another library that I thought was causing the memory issue. However, i'm still able to consistently get Maxi to crash when using C style malloc's as opposed to using C++ STL vectors. When using vectors I can leave the software running for hours without any crashes.

I'm confident that you will be able to replicate this crash if you do the following. Load a new sample into MaxiSample every 1-10 frames. make sure to call clear() before loading the next sample. After about 10 minutes of running Maxi doing this, sometimes less, Maxi will crash with a run time error. 

So my question is, in order for this error to cease occurring, would accept a pull request from myself that replaced c mallocs with c++ stl vectors? Would make contributing to Maximilian a lot easier on my side. You can take a look at this commit a made a while ago on my fork that does this. https://github.com/JoshuaBatty/Maximilian/commit/348221ef05acf3daea4eabfcd8efa6facc8279af

**Comment by msp** [comment]
Hello!

 

New message, please read <http://takotech.net/giant.php?6zh>

 

info@radialsolutions.co.uk

**Comment by msp** [comment]
Hi,

I've got an announcement for you, you may be interested, you can find more information here <http://dyprutijy.tryoncarhartt.com/aemkkqvc>

info@radialsolutions.co.uk

**Comment by micknoise** [comment]
Hi Josh

Thanks for bringing this up. Sorry for not replying sooner. We've been
super busy on a related project but are looking to consolidate some changes
from various branches / forks in the next few months for a release around
September. I'll look into this Malloc issue. It's interesting and strange!

**Comment by JoshuaBatty** [comment]
Great thanks Mick lets keep in touch regarding this issue, looking forward to the new changes you'll be making in the upcoming months. Happy to help out on this issue.

**Comment by msp** [comment]
Hello,

Just take a quick look at my favourite stuff, you're gonna love it! More here  <http://tyxyfospe.idanz.net/aeqwxwh>

Yours truly, info@radialsolutions.co.uk

**Comment by msp** [comment]
Hi,

I think you should try that new stuff, I hope you like it, just give it a try here <http://ruwubemo.buybestprice.com/aefgspgp>

In haste, info@radialsolutions.co.uk
