### ISSUE TITLE
Separate repository for ofxMaxim?

### ISSUE THREAD

**Issue by whg** [micknoise/Maximilian#35]
At the moment all of the core maximillian stuff is duplicated in this repository. Can we create a separate repository for the openFrameworks addon and have the core Maximilian stuff, which lives in this repo as a submodule? 

As well as the benefits in development, it would mean more exposure to the addon via [ofxaddons.com](http://ofxaddons.com), where ofxMaxim is not listed.

**Comment by micknoise** [comment]
Hi Will

Yeah that's a good idea. My only remark would be, have submodules every caused you pain?

**Comment by micknoise** [comment]
We've got a proposed solution to this problem and will be implementing it soon.
