### ISSUE TITLE
is MaxiSample::getLength() correct? 

### ISSUE THREAD

**Issue by JoshuaBatty** [micknoise/Maximilian#41]
I've noticed the sample.length is getting set differently in maxiSample.read() than it is when calling [sample.getLength()](https://github.com/micknoise/Maximilian/blob/master/openFrameworks/ofxMaxim/libs/maximilian.cpp#L1085). 

Also it seems to be a fairly ambiguous method name since getLength() doesn't return any values but it does actually mutate the maxi sample which is pretty surprising.

**Comment by borg** [comment]
I lost a half a day trying to understand odd pitch shifts caused by the getLenth was actually working as a setter. I agree it would be nice to change to more standard behaviour.

**Comment by enedrio** [comment]
same here 

> I lost a half a day trying to understand odd pitch shifts caused by the getLenth was actually working as a setter. I agree it would be nice to change to more standard behaviour.

same here *facepalm*
