### ISSUE TITLE
Maxim

### ISSUE THREAD

**Issue by frantic0** [micknoise/Maximilian#44]
Hi Mick,

it would be nice to have a Stop method for interrupting the grains' playback. 

[0x19f6bf000] AVAudioSession.mm:692:
 -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

This error comes up when the stream is closed while playback is happening, when exiting the app.

```
ofSoundStreamStop();
ofSoundStreamClose();
```

Cheers,
F0

**Comment by micknoise** [comment]
yeah perhaps don't do that.
