### ISSUE TITLE
better instructions about how to include the Accellerate framework on mac os

### ISSUE THREAD

**Issue by edap** [micknoise/Maximilian#45]
Regarding the openFrameworks installing instruction, I think they can be improved as follow:

1) How to link the accellerate framework:
go to your project settings on the target, then to click on Build Phases tab.
Uncollapse the part Link with binaries and click on “+”
You’ll have to find the Accelerate.framework in the list and it will work fine.
via http://julienbayle.net/blog/2012/03/maximilian-audio-library-openframeworks-ios/
2) Explain how to to try out the examples

If you want I can make a PR for the Readme file.

And, many thanks for your work on Maximilian ;)

**Comment by micknoise** [comment]
OK will do thanks!
