### ISSUE TITLE
envelope type in ofxMaxim

### ISSUE THREAD

**Issue by edap** [micknoise/Maximilian#51]
I find a bit confusing the 3 different types that are available for the envelope in ofxMaxim. Naming `maxiEnv`, `ofxMaxiEnvelope` and `maxiEnvelope`. Is there a reason to not unify all of them in one type?
I've used `maxiEnv` because the other 2 don't have the methods for the filters, like`lowres`.
If you want, I could open a PR.
Thanks again for your library and your addon, I find it really useful!

**Comment by micknoise** [comment]
The main reason we're not renaming them is because it will break older code. 

TBH you never need to use the ofx prefix.

**Comment by LiepaKuraite** [comment]
Gavin,

These emails come to the inbox - is this an FYI or cam we mute the thread?

Regards
Chantel
