### ISSUE TITLE
Memory stomp in maxiFFT::setup

### ISSUE THREAD

**Issue by siliconmunky** [micknoise/Maximilian#54]
Hello, I've run into an issue where if you call maxiIFFT::setup with a _fftSize less than _windowSize, the call to fft::genWindow will cause a memory stomp.

This is the section in question, that I believe is wrong, because it's using fftSize instead of windowSize.
```
window = (float*) malloc(fftSize * sizeof(float));
memset(window, 0, fftSize * sizeof(float));
```
Maybe I don't have a clear understanding of how this code is supposed to work, but this seemed wrong to me. Or at a minimum I think that maxiFFT::setup should validate the sizes and catch the case where the memory would be stomp.

**Comment by chriskiefer** [comment]
fixed -   

```
windowSize = _windowSize > fftSize ? _windowSize : fftSize;
```
