### ISSUE TITLE
How to get working on Win10?

### ISSUE THREAD

**Issue by sonicviz** [micknoise/Maximilian#66]
I tried to run the download from https://www.kadenze.com/courses/machine-learning-for-musicians-and-artists-v but it says No Devices Found. 
See https://www.kadenze.com/forums/5-sensors-and-features-generating-useful-inputs-for-machine-learning/threads/audio-driver-problem-with-various_audio_input-on-windows

So I downloaded this repo and ran the VC project. It builds ok but says nothing detected.

However, I have a Steinberg UR 44 (6 input) which works just fine with Live and everything else.

Any ideas? I'd love to try using it with Wekinator as outlined in the course.

ty!

**Comment by sonicviz** [comment]
>>::WINDOWS VISUAL STUDIO 2010 PROJECT
This is in the maximilianTestWindowsVS2010 folder. You will need to install the DirectX SDK, so that the program can use DirectSound.

Is there any chance of getting this working with Windows 10 and Visual Studio 2017?
Afaik DirectX is not included with Win 10 

https://docs.microsoft.com/en-us/windows/desktop/directx-sdk--august-2009-

**Comment by micknoise** [comment]
The windows readme needs updating - thanks for pointing this out. However, the windows example project runs just fine on my machine. RE: getting the device to run on a specific sound output device, the starter code will use your default sound output device, so you should set your device to the default for an easy win.

If you want to select from a range of devices, this will probably require you to set the device parameter in RT-AUDIO, which you can do by editing this line:

parameters.deviceId = dac.getDefaultOutputDevice();

and setting the deviceId to the value that corresponds to your equipment.
