### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by dturner** [micknoise/Maximilian#68]
I've just been watching the talk from the JUCE summit here: https://www.youtube.com/watch?v=H-Av78mtFF4. Looks like a cool DSP library which is simple to integrate.  

I was considering adding Android support to it (I am one of the authors of the [Oboe library](https://github.com/google/oboe) for Android) and was just wondering whether Maximillian was still active?

**Comment by dturner** [comment]
Guessing not then 😞

**Comment by mzed** [comment]
It's somewhat active. Better for fork it, IMHO.
