### ISSUE TITLE
Multivoice Oscillators

### ISSUE THREAD

**Issue by sksar** [micknoise/Maximilian#69]
How to get multiple voices in an Oscillator ? I Browser through the library and I didn't find anything that adds sort of unison and detune to an oscillator. 
I am looking forward to create a Synth using Maximilian and JUCE, but most synths have a feature to add multiple voices and detune them slightly to get a richer sound. (Not to be confused with Polyphony which is multiple notes).

Is There any way to get it working ? Or there is no feature as such ?

**Comment by micknoise** [comment]
You need to use more than one oscillator. Check the polyphonic synth example.
