### ISSUE TITLE
error compilation of example linux gcc 8.3

### ISSUE THREAD

**Issue by rdtor** [micknoise/Maximilian#73]
gcc 1.TestTone.cpp -o ex
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
/usr/bin/ld: /tmp/ccQzJl1b.o: in function `play(double*)':
1.TestTone.cpp:(.text+0x23): undefined reference to `maxiOsc::sinewave(double)'
/usr/bin/ld: /tmp/ccQzJl1b.o: in function `__static_initialization_and_destruction_0(int, int)':
1.TestTone.cpp:(.text+0x6f): undefined reference to `std::ios_base::Init::Init()'
/usr/bin/ld: 1.TestTone.cpp:(.text+0x84): undefined reference to `std::ios_base::Init::~Init()'
/usr/bin/ld: 1.TestTone.cpp:(.text+0x98): undefined reference to `maxiOsc::maxiOsc()'
collect2: error: ld returned 1 exit status

**Comment by kunle-e** [comment]
@rdtor did you ever get this solved? I'm facing the same issue?

**Comment by chriskiefer** [comment]
> @rdtor did you ever get this solved? I'm facing the same issue?

this issue is about to be fixed in the next commit
