### ISSUE TITLE
maxiFlanger/maxiChorus don't seem to work properly

### ISSUE THREAD

**Issue by cuinjune** [micknoise/Maximilian#74]
When I use `maxiFlanger` or `maxiChorus`, they are glitchy and doesn't sound natural.

Maybe this is why there are comments saying `//todo: needs fixing` inside `maxiFlanger::flange`  and `maxiChorus::chorus` functions?

It would be nice if they can be fixed.

**Comment by micknoise** [comment]
Thanks - I'll take a look, although there's nothing that complex about them. If you need a flanger, you can use a delay line with a short delay and lots of feedback.
