### ISSUE TITLE
maxiEnvelope::adsr

### ISSUE THREAD

**Issue by mzed** [micknoise/Maximilian#79]
There are three ways to call maxiEnvelope::adsr  Two of them take the input signal, and return an enveloped version. One just returns phase.  This is a bit confusing.  Maybe there should be a single way envelopes operate in Maxi?  Is it:

output = mySound * myEnvelope()

or

output = myEnvelope(mySound)

?

**Comment by chriskiefer** [comment]
fixed in maxiEnvGen
