### ISSUE TITLE
phaseReset from the maxiOsc class doesn't seem to work

### ISSUE THREAD

**Issue by rigomapoga** [micknoise/Maximilian#81]
Using the member function of the maxiOsc class "phaseReset" seems to corrupt the functioning of the oscillator (only a series of very short glitches comes out when the phase value gets changed from 0. to 1.).
I haven't found a better place than this to to post this issues, I hope to get some help getting this phaseReset working. All I want is a way to apply a phase rotation to the wave.
Thanks,

**Comment by mzed** [comment]
I don't see anything obviously wrong with this function. (It's dead simple.) Could you post some steps to reproduce your problem? What waveform are you testing with?
