### ISSUE TITLE
maxiConvolve trying to access private member of maxFFT

### ISSUE THREAD

**Issue by PavlosChatz** [micknoise/Maximilian#85]
It seems that maxiConvolve code tries to access private member of maxiFFT/ maxiIFFT "bins". There is a public member function of maxiFFT returning the number of bins. Such a member function does not exist for maxiIFFT. Can I work on this to add a getNumBins member function to maxiIFFT and change the code in maxConvolve from fft.bins to fft.getNumBins?

**Comment by chriskiefer** [comment]
Hi Pavlos, thanks that would be really helpful.  Chris

**Comment by PavlosChatz** [comment]
Hello Chris, I created a pull request with this fix. Pavlos
