### ISSUE TITLE
Maxifilter Lores broken above ~9khz. Saw someone have same problem on OFMaxim

### ISSUE THREAD

**Issue by mikegao4005** [micknoise/Maximilian#94]
Anyone else have issue with Maxifilter Lores broken above ~9khz. Saw someone have same problem on OFMaxim
I set the right sample rate etc hmm

**Comment by micknoise** [comment]
Yeah it was originally written to work on an iPhone 3G as a baseline and that meant being a bit dirty. The algorithm can support maximum CF of around 11k (or at least it should) but the quick fix is to er, um, not put in large numbers.
