### ISSUE TITLE
MaximExtractorExample compile error on RasPi

### ISSUE THREAD

**Issue by okyeron** [micknoise/Maximilian#98]
I am having a go a modifying the OSX/OF0.8.4MaximExtractorExample to work with OF 0.11.0 and RasPi 

Getting the following compile error with regards to maxiMFCC.h

```
inlined from ‘virtual void ofApp::setup()’ at /home/pi/openFrameworks/addons/ofxMaxim/MaximExtractorExample/src/ofApp.cpp:65:15:
/home/pi/openFrameworks/addons/ofxMaxim/MaximExtractorExample/ofxMaxim/libs/maxiMFCC.h:140:27: warning: argument 1 value ‘4294959104’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
   melFilters = (T*) malloc(sizeof(T) * numFilters * numValidBins);
                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

OF 0.11.0
RasPi 4b with 5.4.83-v7l+
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

Otherwise - is there a more recent Example that shows the audio analysis functions?

**Comment by okyeron** [comment]
FWIW - I was able to get compiled and running by doing

`melFilters = (T*) malloc(sizeof(double) * numFilters * numValidBins);`

based on the `filtPos` bit on line 129

**Comment by micknoise** [comment]
That will work if you are using doubles.
