### ISSUE TITLE
bugs on maxiRatioSeq playValues values?

### ISSUE THREAD

**Issue by frantic0** [micknoise/Maximilian#99]
I tracked down a very fine-grained bug in sema. It seems that an rsq sequence is executed in an incorrect order 

https://github.com/mimic-sussex/sema/issues/292

could you confirm, @chriskiefer? 

thanks

**Comment by frantic0** [comment]
```
// get a note sequence
:seq:{1}fromJS;

// play the note sequence
// :freq:{{16}clt, [1], :seq:}rsq;

:freq:{{16}clt, [1], [440, 440, 440, 440, 3135.9634878539946, 3520, 440, 880, 369.99442271163446, 440, 440, 3951.066410048992]}rsq;
>{:freq:}tri;
```

**Comment by chriskiefer** [comment]
> I found another problem with rsq.
> 
> It seems that whenever you pass a variable (referencing an array, instead of the actual array) it truncates the value (i.e. it only loops the first n elements)
> 
> ```
> // get a note sequence
> :seq:{1}fromJS;
> 
> // play the note sequence
> // :freq:{{16}clt, [1], :seq:}rsq;
> 
> // the same array that should come on :seq: is hardcoded and rsq works well here  
> :freq:{{16}clt, [1], [440, 440, 440, 440, 3135.9634878539946, 3520, 440, 880, 369.99442271163446, 440, 440, 3951.066410048992]}rsq;
> >{:freq:}tri;
> ```


could you clarify the bug a bit - what is the 'first n elements'?  perhaps you could post the js side as well? 

it looks like rsq should respond to variable length arrays so this is probably some sort of difference between constant and variable arrays in the language side - we'll need to take a look at the code that gets generated
